

export default async (models) => {
    const locationList = [
        {
            name: "Cat Paradise",
            city: "Milan"
        },
        {
            name: "Cat City",
            city: "Rome"
        }
    ]
    const location0 = await models.Location.create(locationList[0])
    const location1 = await models.Location.create(locationList[1])
    const catList = [
        {
            name: "Cat 1",
            breed: "Siberian",
            description: "Details about cat 1",
            img: "https://fs.i3lab.group/hypermedia/cats/siberian.jpg",
            locationId: location0.id
        },
        {
            name: "Cat 2",
            breed: "Birman",
            description: "Details about cat 2",
            img: "https://fs.i3lab.group/hypermedia/cats/birman.jpg",
            locationId: location0.id
        },
        {
            name: "Cat 3",
            breed: "Bombay",
            description: "Details about cat 3",
            img: "https://fs.i3lab.group/hypermedia/cats/bombay.jpg",
            locationId: location0.id
        },
        {
            name: "Cat 4",
            breed: "Calico",
            description: "Details about cat 4",
            img: "https://fs.i3lab.group/hypermedia/cats/calico.jpg",
            locationId: location1.id
        },
        {
            name: "Cat 5",
            breed: "Maine Coon",
            description: "Details about cat 5",
            img: "https://fs.i3lab.group/hypermedia/cats/maine-coon.jpg",
            locationId: location1.id
        },
    ]
    await models.Cat.bulkCreate(catList)

    const POIs = [
        {
            imgPathMain: "https://images.unsplash.com/photo-1634080782716-ad30ba56266e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "Notre Dame Basilica",
            address: "110, Notre-Dame Street West Montréal (Québec) H2Y 1T1 Canada",
            hours: "9 AM - 4 PM",
            cost: "$14",
            imgPathText: "https://images.unsplash.com/photo-1561306774-ce2d895584f5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.basiliquenotredame.ca/en",
            hosts: "Luminotherapie",
            itinerary: "1",
            Neighbourhood: "East",
            poiName: "Montreal Symphony House",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1655720035861-ba4fd21a598d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Phi Centre",
            address: "315, rue Saint-Paul O., Montreal, QC",
            hours: "Opening hours vary according to each exhibit",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1609278406593-363130c99995?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://phi.ca/en/whats-on/",
            hosts: "Infinity Mirror Rooms",
            itinerary: "4",
            Neighbourhood: "South",
            poiName: "Montreal Symphony House",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.squarespace-cdn.com/content/v1/5afb5bb0fcf7fd7aebb47cac/1628025458667-BVXM8LKZ786KUIR14XZ5/cafe%CC%81_arsenal_art+contemporain_contemporary+art+montreal_2020_5.jpg?format=1000w",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Arsenal Contemporary Art",
            address: "2020 rue William, Montreal, QC",
            hours: "10 AM - 7 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1634937469229-b8a4cdb47c60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://www.arsenalcontemporary.com/",
            hosts: " ",
            itinerary: "4",
            Neighbourhood: "West",
            poiName: "Satosphere",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1625954136459-3c52e40bbc5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "St. Joseph's Oratory",
            address: "3800 Queen Mary Road Montréal (Quebec) Canada, H3V 1H6",
            hours: "6:30 AM - 9 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1592615666002-5d4dbbcd6195?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.saint-joseph.org/en/",
            hosts: "Cinéma sous les Étoiles",
            itinerary: "1",
            Neighbourhood: "East",
            poiName: "La Guilde",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1551535781-89a901c6ef91?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            descriptionMain: "This outdoor space is equally enjoyable as a solo traveller or in a group. There's something for everyone. Go earlier in the day if possible to avoid crowds. The nearest metro station is only a 5 minute walk, but paid parking is also available on site.",
            heading: "Cemetery of Mont Royal",
            address: "1297 Chemin de la Forêt, Outremont, Québec H2V 2P9",
            hours: "8 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1588702102250-e0187b3735f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "outdoor",
            url: "https://www.mountroyalcem.com/index.php/en/",
            hosts: " ",
            itinerary: "3",
            Neighbourhood: "South",
            poiName: "Le Saint Motel",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1649127099817-d23073cabce9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "Our Lady of the Harbor",
            address: "400 Rue Saint-Paul E, Montréal, QC H2Y 1H4, Canada",
            hours: "10 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1656297825905-2ddcaf8f289c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.diocesemontreal.org/en/lets-connect/churches-parishes/notre-dame-de-bon-secours-chapelle",
            hosts: "Japanese Cultural Festival",
            itinerary: "1",
            Neighbourhood: "South",
            poiName: "Notre Dame Basilica",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1651461308816-7f4ae3eda599?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "Mary Queen of the World",
            address: "1085, rue de la Cathédrale Montréal (Qc) H3B 2V3",
            hours: "7 AM - 7 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1571844437758-9e7bb9a5fdf6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1315&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.diocesemontreal.org/en/lets-connect/churches-parishes/mary-queen-world-cathedral",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "East",
            poiName: "Montreal Symphony House",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1629213761741-088d9eeffa9a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "St. Patrick's Basilica",
            address: "460 René Lévesque Blvd. West, Montreal, Quebec, Canada H2Z 1A7",
            hours: "10 AM - 4 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1550541231-56ddb7f844ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "http://stpatricksmtl.ca/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "Botanical Gardens",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1562987147-615e68d2e32e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "Christ Church Cathedral",
            address: "635 Saint-Catherine St W, Montreal, Quebec H3A 2B8, Canada",
            hours: "10 AM - 4 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1588639244228-d27de71b59f7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=709&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.montrealcathedral.ca/",
            hosts: "Asian Dessert and Craft Market",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Oasis",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1633615867142-48d30fe756bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "St. James United Church",
            address: "463 Saint-Catherine St W, Montreal, Quebec H3B 1B1, Canada",
            hours: "10 AM - 4 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1630004498173-009c8876b936?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "http://stjamesmontreal.ca/stjames_church/who_we_are.html",
            hosts: "Pop Montreal",
            itinerary: "0",
            Neighbourhood: "East",
            poiName: "Jean Talon",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1549929966-ad70a3a79ea5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            descriptionMain: "Finished in 1829, this church is an irreplaceable fixture of the Montreal skyline. And while many come to worship, the church is also well known for hosting concerts enjoyed by all members of the Montreal community. Tours are welcome outside of mass hours. Check in on the official website, as markets and special events are common throughout the year. Just don't forget - please keep your voices down as you visit!",
            heading: "Church of St. Peter the Apostle",
            address: "1201, Visitation Street Montreal (Qc) H2L 3B5",
            hours: "11 AM - 5 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1644173728840-810c9e0d4db9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "churches",
            url: "https://www.diocesemontreal.org/en/lets-connect/churches-parishes/saint-pierre-apotre",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "Montreal Symphony House",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1650327034446-897929c7fd66?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=686&q=80",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Oasis",
            address: "Palais des congrès de Montréal 301 Saint-Antoine St West, Montréal, Québec H2Z 1H5",
            hours: "Hours vary according to exhibit",
            cost: "See exhibit rates",
            imgPathText: "https://images.unsplash.com/photo-1601828400231-4694b2dd872d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://oasis.im/",
            hosts: "Van Gogh",
            itinerary: "4",
            Neighbourhood: "West",
            poiName: "Atwater",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1648859477841-6aed1c18673e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80",
            descriptionMain: "This outdoor space is equally enjoyable as a solo traveller or in a group. There's something for everyone. Go earlier in the day if possible to avoid crowds. The nearest metro station is only a 5 minute walk, but paid parking is also available on site.",
            heading: "Botanical Gardens",
            address: "4101 Sherbrooke St E, Montreal, Quebec H1X 2B2, Canada",
            hours: "9 AM - 6 PM",
            cost: "$22",
            imgPathText: "https://images.unsplash.com/photo-1644276134614-c82ec69dfe26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "outdoor",
            url: "https://espacepourlavie.ca/en/botanical-garden ",
            hosts: "Gardens of light",
            itinerary: "3",
            Neighbourhood: "East",
            poiName: "La Guilde",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1565922243372-e178d3128353?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Le Saint Motel",
            address: "4000 St-Ambroise, Suite 278",
            hours: "11 AM - 6 PM",
            cost: "$30",
            imgPathText: "https://images.unsplash.com/photo-1630192784641-aa87b3f817e2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://lesaintmotel.com/",
            hosts: "The Sky Belongs to the DJ",
            itinerary: "4",
            Neighbourhood: "South",
            poiName: "New City Gas",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1547401061-7fbd33ec9021?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Satosphere",
            address: "1201 St Laurent Blvd, Montreal, Quebec H2X 2S6, Canada",
            hours: "10 AM - 10 PM",
            cost: "See exhibit rates.",
            imgPathText: "https://images.unsplash.com/photo-1486744328743-c1151100a95b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://sat.qc.ca/en/satosphere",
            hosts: "Cine-Concerts",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Church of St. Peter the Apostle",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1641407959416-4b5f9c634d12?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            descriptionMain: "While this museum has a lot to offer on the inside, it's worth a look at the beautiful exterior, a timeless part of the fabric of Montreal. While the rotating exhibits are always fascinating, the permanent collection is a must-see if you are short on time. Enjoy a drink at the cafe on the frst floor if you're tired after your visit. ",
            heading: "Musee des Beaux-Arts",
            address: "1380 Sherbrooke St W, Montreal, Quebec H3G 1J5, Canada",
            hours: "10 AM - 9 PM",
            cost: "$16 - $24",
            imgPathText: "https://images.unsplash.com/photo-1479069938554-5c7a6ee560af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "museums",
            url: "https://www.mbam.qc.ca/en/",
            hosts: " ",
            itinerary: "2",
            Neighbourhood: "East",
            poiName: "Phi Centre",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1599140427277-7cbcb58180a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80",
            descriptionMain: "While this museum has a lot to offer on the inside, it's worth a look at the beautiful exterior, a timeless part of the fabric of Montreal. While the rotating exhibits are always fascinating, the permanent collection is a must-see if you are short on time. Enjoy a drink at the cafe on the frst floor if you're tired after your visit. ",
            heading: "McCord Museum",
            address: "690 Sherbrooke St W, Montreal, Quebec H3A 1E9, Canada",
            hours: "10 AM - 5 PM",
            cost: "$14 - $19",
            imgPathText: "https://images.unsplash.com/photo-1569783721854-33a99b4c0bae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1128&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "museums",
            url: "https://www.musee-mccord.qc.ca/en/",
            hosts: " ",
            itinerary: "2",
            Neighbourhood: "South",
            poiName: "point-a-Calliere",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "While this museum has a lot to offer on the inside, it's worth a look at the beautiful exterior, a timeless part of the fabric of Montreal. While the rotating exhibits are always fascinating, the permanent collection is a must-see if you are short on time. Enjoy a drink at the cafe on the frst floor if you're tired after your visit. ",
            heading: "Point-a-Calliere",
            address: "Pointe-à-Callière, 350 Place Royale, Montreal, QC",
            hours: "10 AM - 6 PM",
            cost: "$17 - $25",
            imgPathText: "https://images.unsplash.com/photo-1583134679724-6e395f4068ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "museums",
            url: "https://pacmusee.qc.ca/fr/30ans/",
            hosts: "3GIANTS",
            itinerary: "2",
            Neighbourhood: "West",
            poiName: "Les Grand Ballets",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1594909841201-91e03684a450?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80",
            descriptionMain: "While this museum has a lot to offer on the inside, it's worth a look at the beautiful exterior, a timeless part of the fabric of Montreal. While the rotating exhibits are always fascinating, the permanent collection is a must-see if you are short on time. Enjoy a drink at the cafe on the frst floor if you're tired after your visit. ",
            heading: "Museum of Contemporary Art",
            address: "1 Place Ville Marie, Montreal, Quebec H3B 3Y1, Canada",
            hours: "11:30 AM - 7 PM",
            cost: "$10",
            imgPathText: "https://images.unsplash.com/photo-1586489637577-c47b12fd3819?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "museums",
            url: "https://macm.org/en/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "East",
            poiName: "Botanical Gardens",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1558486548-8a98b1077ad1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "While this museum has a lot to offer on the inside, it's worth a look at the beautiful exterior, a timeless part of the fabric of Montreal. While the rotating exhibits are always fascinating, the permanent collection is a must-see if you are short on time. Enjoy a drink at the cafe on the frst floor if you're tired after your visit. ",
            heading: "Canadian Centre for Architecture",
            address: "1920 Baile St, Montreal, Quebec H3H 2S6",
            hours: "11 AM - 6 PM",
            cost: "$10",
            imgPathText: "https://images.unsplash.com/photo-1653839644279-65c073aac0de?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "museums",
            url: "https://www.cca.qc.ca/en/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "Oasis",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1537021851688-be44f66c1044?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            descriptionMain: "This outdoor space is equally enjoyable as a solo traveller or in a group. There's something for everyone. Go earlier in the day if possible to avoid crowds. The nearest metro station is only a 5 minute walk, but paid parking is also available on site.",
            heading: "Atwater",
            address: "138 Atwater Ave, Montreal, Quebec H4C 2H6, Canada",
            hours: "9 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1540289917366-db90f08d2397?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1485&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "markets",
            url: "https://www.marchespublics-mtl.com/en/marches/atwater-market/",
            hosts: "Film Noir au Canal",
            itinerary: "3",
            Neighbourhood: "West",
            poiName: "jean Talon",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1578254376187-301185b05b66?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "This outdoor space is equally enjoyable as a solo traveller or in a group. There's something for everyone. Go earlier in the day if possible to avoid crowds. The nearest metro station is only a 5 minute walk, but paid parking is also available on site.",
            heading: "Jean Talon",
            address: "7070 Henri Julien Ave, Montreal, Quebec H2S 3S3, Canada",
            hours: "8 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1586445082539-58a3a0a7ea8e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "markets",
            url: "https://www.marchespublics-mtl.com/en/marches/jean-talon-market/",
            hosts: "Igloofest",
            itinerary: "3",
            Neighbourhood: "East",
            poiName: "Atwater",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "Galerie 203",
            address: "227, rue Notre-Dame O., Montreal, QC",
            hours: "10 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1594794312433-05a69a98b7a0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://galerie203.com/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "Montreal Symphony House",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1584448141569-69f342da535c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=741&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "L'Affichiste",
            address: "461, rue Saint Francois Xavier, Montreal, QC",
            hours: "10 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1613759007428-9d918fe2d36f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://www.laffichiste.com/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Theatre Maisonneuve",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1635982751661-c783248f4dd5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "La Guilde",
            address: "1356, rue Sherbrooke O., Montreal, QC",
            hours: "10 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1639037401481-52c03ed0a6a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://laguilde.com/",
            hosts: "Envolées Latines",
            itinerary: "2",
            Neighbourhood: "East",
            poiName: "Our Lady of the Harbor",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1635982745302-bc6084c6a850?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "Bradley Ertaskiran",
            address: "3550, rue Saint-Antoine O., Montreal, QC",
            hours: "11 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1565799515768-2dcfd834625c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1519&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://bradleyertaskiran.com/en/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "St. Joseph's Oratory",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1572620645236-854a94b83040?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "L'Original Vernissage",
            address: "4455, rue Saint-Denis, Montreal, QC",
            hours: "10 AM - 4 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1570479842645-74473481e11b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://www.loriginal.org/",
            hosts: " ",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Notre Dam Basilica",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1583414551896-14baf5cf0052?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80",
            descriptionMain: "Getting to know the local art is a great way to understand the culture and mentality of a city, and this gallery offers exactly that. This gallery made it's name by offering a space to a genre of Canadian artists that did not previously has a platform. Years in, it's still going strong. If you stop by in the evening hours, you might be lucky enough to find one of the artists hosting event! Check their official website for details. ",
            heading: "Galerie FOFA",
            address: "1515, rue Sainte-Catherine O. EV 1-715, Montreal, QC",
            hours: "11 AM - 6 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1654966199325-ed70abd874df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://www.concordia.ca/finearts/facilities/galerie-fofa.html",
            hosts: " ",
            itinerary: "2",
            Neighbourhood: "East",
            poiName: "Le Saint Motel",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1634937469229-b8a4cdb47c60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            descriptionMain: "You've never seen anything like this before. An art exhibit, but you're part of it! Walk through the immersive rooms and get behind the motivations and emotions of this world famous artist. And, if you have time, snap a photo! This is a memory you wont want to forget. Check the official website to book your time slot. ",
            heading: "Arsenal Art Contemporain",
            address: " 2020, rue William, Montreal, QC",
            hours: "10 AM - 7 PM",
            cost: "Free",
            imgPathText: "https://images.unsplash.com/photo-1634937469229-b8a4cdb47c60?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "galleries",
            url: "https://www.arsenalcontemporary.com/mtl/home",
            hosts: "Frida Kahlo: An Immersive Biography",
            itinerary: "4",
            Neighbourhood: "South",
            poiName: "New City Gas",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1574551375004-f46a1d1cca53?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            descriptionMain: "This music venue is an iconic part of Montreal's history. Arrive early to get a drink at the bar. While there's no dress code, it's a great excuse to dress the part! Be sure to check the official website for the current lineup of shows. The venue is situated close to a metro stop, so transport to all major neighbourhoods and hotels is a breeze. ",
            heading: "Montreal Symphony House",
            address: "1600 Rue Saint-Urbain, Montréal, QC H2X 0S1, Canada",
            hours: "Hours vary according to performance",
            cost: "See performance rates",
            imgPathText: "https://images.unsplash.com/photo-1610504782444-2695d239ef67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "music",
            url: "https://placedesarts.com/en",
            hosts: "Rafael Payare Conducts Shostakovich, Ravel, and Liszt ",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Arsenal Art Contemporain",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1495109251996-432ef0887b37?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1176&q=80",
            descriptionMain: "This music venue is an iconic part of Montreal's history. Arrive early to get a drink at the bar. While there's no dress code, it's a great excuse to dress the part! Be sure to check the official website for the current lineup of shows. The venue is situated close to a metro stop, so transport to all major neighbourhoods and hotels is a breeze. ",
            heading: "Les Grand Ballets",
            address: "175 Saint-Catherine St W, Montreal, Quebec H2X 1Y9, Canada",
            hours: "Hours vary according to performance",
            cost: "See performance rates",
            imgPathText: "https://images.unsplash.com/photo-1586117652181-1e68b751cc1b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "music",
            url: "https://grandsballets.com/en/ ",
            hosts: "The Nutcracker",
            itinerary: "0",
            Neighbourhood: "East",
            poiName: "La Guilde",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1630050525402-06c617847d27?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            descriptionMain: "This music venue is an iconic part of Montreal's history. Arrive early to get a drink at the bar. While there's no dress code, it's a great excuse to dress the part! Be sure to check the official website for the current lineup of shows. The venue is situated close to a metro stop, so transport to all major neighbourhoods and hotels is a breeze. ",
            heading: "Theatre Maisonneuve",
            address: "260 Boul. de Maisonneuve Ouest 2nd floor, Montréal, QC H2X 1Y9, Canada",
            hours: "Hours vary according to performance",
            cost: "See performance rates",
            imgPathText: "https://images.unsplash.com/photo-1576679922462-75304c3525dc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "music",
            url: "https://placedesarts.com/fr/salle/th%C3%A9%C3%A2tre-maisonneuve",
            hosts: "Movie Fridays at the Grande Bibliotheque",
            itinerary: "0",
            Neighbourhood: "South",
            poiName: "St. james United Church",
            eventId: 2,
            
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1570872626485-d8ffea69f463?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
            descriptionMain: "This music venue is an iconic part of Montreal's history. Arrive early to get a drink at the bar. While there's no dress code, it's a great excuse to dress the part! Be sure to check the official website for the current lineup of shows. The venue is situated close to a metro stop, so transport to all major neighbourhoods and hotels is a breeze. ",
            heading: "New City Gas",
            address: "950 Ottawa St, Montreal, Quebec H3C 1S4, Canada",
            hours: "12 PM - 9 PM",
            cost: "$22",
            imgPathText: "https://images.unsplash.com/photo-1559666201-29411f21bf59?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            category: "immersive",
            url: "https://newcitygas.com/",
            hosts: "Intangible Forms",
            itinerary: "0",
            Neighbourhood: "West",
            poiName: "Satosphere",
            eventId: 2,
            
        },

    ]
    await models.POI.bulkCreate(POIs)

    const Event = [
        {
            imgPathMain: "https://images.unsplash.com/photo-1626243048879-51f8d9818566?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here. ",
            heading: "Van Gogh",
            address: "Palais des congrès de Montréal, 301 rue Saint-Antoine O., Montreal, QC",
            season: "summer",
            month: "August",
            dates: "10th",
            hours: "10 AM - 5 PM",
            cost: "$26",
            url: "https://oasis.im/",
            hostedIn: "Oasis",
            poiId: 1,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1629305087164-48502f92c640?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.",
            heading: "Infinity Mirror Rooms",
            address: "PHI Foundation for Contemporary Art, 451 & 465 rue Saint-Jean",
            season: "winter",
            month: "November",
            dates: "1st - 26th",
            hours: "10 AM - 5 PM",
            cost: "Free",
            url: "https://phi.ca/en/events/yayoi-kusama/",
            hostedIn: "Phi Centre",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1545732652-0ccca98d7fd9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event is relatively young, but is returning thanks to it's popularity last year. It has also expanded, adding new vendors and artists to the roster. Try to show up early in the day to avoid crowds.",
            heading: "Intangible Forms",
            address: "950 Ottawa St, Montreal, Quebec H3C 1S4, Canada",
            season: "summer",
            month: "May",
            dates: "1st - 26th",
            hours: "10 AM - 7 PM",
            cost: "$22",
            url: "https://intangibleforms.com/",
            hostedIn: "New City Gas",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1592434060723-7a8d00ab3dc9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.",
            heading: "Frida Kahlo: An Immersive Biography",
            address: "Arsenal Contemporary Art, 2020 rue William, Montreal, QC",
            season: "summer",
            month: "June",
            dates: "10th - 14th",
            hours: "10 AM - 7 PM",
            cost: "$33",
            url: "https://fridakahlomontreal.com/",
            hostedIn: "Arsenal Art Contemporain",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event. ",
            heading: "Igloofest",
            address: "1 Circuit Gilles Villeneuve, Montréal, QC H3C 1A9, Canada",
            season: "winter",
            month: "February",
            dates: "4th",
            hours: "Hours vary according to performance",
            cost: "$44",
            url: "https://igloofest.ca/en",
            hostedIn: "Jean Talon",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1650570594108-07c2fbbbb98e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1175&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event. ",
            heading: "Luminotherapie",
            address: "1201, Rue Saint-Dominique Montreal, QC H2X 2W3",
            season: "winter",
            month: "January",
            dates: "6th",
            hours: "9 AM - 5 PM",
            cost: "Free",
            url: "https://www.quartierdesspectacles.com/en/event/290/luminotherapie-12th-edition/",
            hostedIn: "Notre Dame Basilica",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1618123664298-f3a0281e7e44?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event. ",
            heading: "Cine-Concerts",
            address: "1201 St Ladescriptionurent Blvd, Montreal, Quebec H2X 2S6, Canada",
            season: "summer",
            month: "July",
            dates: "17th - 21st",
            hours: "8 PM",
            cost: "Free",
            url: "https://placedesarts.com/en/theme/cine-concert",
            hostedIn: "Satosphere",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1588516903875-f5f91fea559a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=781&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured films for each day of the event. ",
            heading: "Film Noir au Canal",
            address: "1335 Rue Saint-Patrick Montréal, QC H3K 1A4",
            season: "summer",
            month: "July",
            dates: "13th - 23rd",
            hours: "7:30 PM",
            cost: "Free",
            url: "https://www.facebook.com/FilmNoirauCanal",
            hostedIn: "Atwater",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1527979809431-ea3d5c0c01c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1509&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured films for each day of the event. ",
            heading: "Cinéma sous les Étoiles",
            address: "4355 Rue Fullum Montréal, QC H2H 1N1",
            season: "winter",
            month: "September",
            dates: "6th - 29th",
            hours: "9 PM",
            cost: "Free",
            url: "https://cinemasouslesetoiles.org/",
            hostedIn: "St. Joseph's Oratory",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1536190966671-59537a3dea90?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event. ",
            heading: "Movie Fridays at the Grande Bibliotheque",
            address: " 475 Boul. de Maisonneuve E, Montréal, QC H2L 5C4, Canada",
            season: "summer",
            month: "August",
            dates: "Friday evenings",
            hours: "8 PM",
            cost: "Free",
            url: "https://www.mtl.org/en/what-to-do/heritage-and-architecture/grande-bibliotheque-bibliotheque-et-archives-nationales-du",
            hostedIn: "Theatre Maisonneuve",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1524619201032-8590e48bac19?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=716&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.  ",
            heading: "Asian Dessert and Craft Market",
            address: "2077 Blvd Robert-Bourassa, Montréal, QC H3A 2M3, Canada",
            season: "summer",
            month: "April",
            dates: "2nd",
            hours: "11 AM - 5 PM",
            cost: "Free",
            url: "https://lemajesthe.ca/",
            hostedIn: "Church of St. Peter the Apostle",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1542822670-b7fb7632b23a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event is relatively young, but is returning thanks to it's popularity last year. It has also expanded, adding new vendors and artists to the roster. Try to show up early so the most instagram famous snacks won't be out!",
            heading: "Japanese Cultural Festival",
            address: "Marché des Possibles and Warehouse 77, 77, rue Bernard E., Montreal, QC",
            season: "summer",
            month: "June",
            dates: "10th - 12th ",
            hours: "10 AM - 6 PM",
            cost: "Free",
            url: "https://www.yataimtl.com/",
            hostedIn: "Our Lady of the Harbor",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1502872364588-894d7d6ddfab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event. ",
            heading: "The Sky Belongs to the DJ",
            address: "22, Chemin Macdonald, Montreal, QC",
            season: "summer",
            month: "June",
            dates: "12th - 23rd ",
            hours: "10 PM",
            cost: "Free",
            url: "https://www.laronde.com/larondefr/linternational-des-feux",
            hostedIn: "Le Saint Motel",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1572252698222-3ce9dcc32888?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.",
            heading: "3GIANTS",
            address: "Esplanade Place Ville Marie, Jardins Gamelins, and Parc Vinet",
            season: "summer",
            month: "July",
            dates: "7th - 17th",
            hours: "6 PM and 9 PM",
            cost: "Free",
            url: "https://montrealcompletementcirque.com/en/p/the-3-giants/",
            hostedIn: "Point-a-Calliere",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1519682718457-c82ce8296645?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.",
            heading: "Rafael Payare Conducts Shostakovich, Ravel, and Liszt ",
            address: "1600 Rue Saint-Urbain, Montréal, QC H2X 0S1, Canada",
            season: "winter",
            month: "October",
            dates: "12th",
            hours: "7:30 PM",
            cost: "$25 - $210",
            url: "https://www.osm.ca/en/home-osm/",
            hostedIn: "Montreal Symphony House",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1495791185843-c73f2269f669?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event comes highly recommended for visitors with families and young children. All ages are welcome, and kids under 10 attend for free. The venue often hosts special activities on weekends, so check the website if you want to make a day out of your visit here.",
            heading: "The Nutcracker",
            address: "175 Saint-Catherine St W, Montreal, Quebec H2X 1Y9, Canada",
            season: "winter",
            month: "December",
            dates: "9th - 30th",
            hours: "2 PM and 7:30 PM",
            cost: "$57 - $149",
            url: "https://grandsballets.com/en/performances/detail/nutcracker/",
            hostedIn: "Les Grand Ballets",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1586853233601-8dc7c8bbf0e8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=626&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "This event is relatively young, but is returning thanks to it's popularity last year. It has also expanded, adding new artists to the festival. Try to show up early to hear the artists speak before the performance.",
            heading: "Envolées Latines",
            address: "175 Saint-Catherine St W, Montreal, Quebec H2X 1Y9, Canada",
            season: "winter",
            month: "November",
            dates: "4th",
            hours: "7:30 PM",
            cost: "$33 - $169",
            url: "https://orchestremetropolitain.com/fr/concerts/envolees-latines/?show_date_id=4190",
            hostedIn: "La Guilde",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1591980848793-35f175a0e2d0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night. Check the official website for details on featured artists for each day of the event.",
            heading: "Pop Montreal",
            address: "175 Saint-Catherine St W, Montreal, Quebec H2X 1Y9, Canada",
            season: "winter",
            month: "September",
            dates: "28th",
            hours: "8 PM",
            cost: "$12",
            url: "https://popmontreal.com/",
            hostedIn: "St. James United Church",
            poiId: 5,
        },
        {
            imgPathMain: "https://images.unsplash.com/photo-1644312816637-eb0815f5a576?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
            description: "City locals wait all year for the return of this event, so you're in luck if you happen to be visiting at the right time. Come prepared for the weather, as temperatures can be very chilly, especially as the event runs late into the night.",
            heading: "Gardens of light",
            address: "4101 Sherbrooke St E, Montreal, Quebec H1X 2B2, Canada",
            season: "winter",
            month: "October",
            dates: "12th",
            hours: "7 PM",
            cost: "$17",
            url: "https://espacepourlavie.ca/en/chinese-garden",
            hostedIn: "Botanical Gardens",
            poiId: 5,
        },

    ]
    await models.Event.bulkCreate(Event)

    const Service = [
        {
            heading: "Bixi",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://bixi.com/",
            type: "Transportation in the City",
            Neighbourhood: "East",
        },
        {
            heading: "Exo",
            location: "700 rue de la Gauchetière, Montreal, Quebec, Canada",
            hours: "6 AM - 8:30 PM",
            url: "https://exo.quebec/en",
            type: "Transportation in the City",
            Neighbourhood: "East",
        },
        {
            heading: "Metro",
            location: "800, rue de la Gauchetiere Ouest; Montreal, Quebec; H5A 1J6",
            hours: "5:30 AM to 1 AM",
            url: "https://www.stm.info/en/info/networks/metro",
            type: "Transportation in the City",
            Neighbourhood: "South",
        },
        {
            heading: "Uber",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://www.uber.com/global/en/cities/montreal/",
            type: "Transportation in the City",
            Neighbourhood: "West",
        },
        {
            heading: "Montreal Scooter",
            location: "520 Rue Berri\nMontréal, QC H2Y 1B4",
            hours: "10:30 AM - 6:30 PM",
            url: "https://www.montrealscooter.com/",
            type: "Transportation in the City",
            Neighbourhood: "East",
        },
        {
            heading: "BlablaCar",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://www.uber.com/global/en/cities/montreal/",
            type: "Transportation in the City",
            Neighbourhood: "South",
        },
        {
            heading: "Les Amis de la Montagne",
            location: "1260, chemin Remembrance\nMontréal (Québec) H3H 1A2",
            hours: "9:30 AM - 4:30 PM",
            url: "https://www.lemontroyal.qc.ca/en/mount-royal-park-visitor-services",
            type: "Outdoor Fun",
            Neighbourhood: "East",
        },
        {
            heading: "Quantum e-bikes",
            location: "115 Atwater Avenue Montreal, QC H3J 2Z8",
            hours: "10 AM - 5 PM",
            url: "https://www.quantumebikes.com/en/",
            type: "Outdoor Fun",
            Neighbourhood: "South",
        },
        {
            heading: "Patin Patin",
            location: "Pavillon Bonsecours\n364 de la Commune East street\nMontreal (Quebec) H2Y 1J3",
            hours: "9 AM - 10 PM",
            url: "https://www.patinpatin.ca/en/old-port-montreal-skating-rink/",
            type: "Outdoor Fun",
            Neighbourhood: "West",
        },
        {
            heading: "Kids Help Phone",
            location: "Available by telephone at 1-800-668-6868",
            hours: "24/7",
            url: "https://kidshelpphone.ca/",
            type: "Safety",
            Neighbourhood: "East",
        },
        {
            heading: "Suicide Action Montreal",
            location: "Available by telephone +1 866-277-3553",
            hours: "24/7",
            url: "https://suicideactionmontreal.org/en/",
            type: "Safety",
            Neighbourhood: "South",
        },
        {
            heading: "Nightline",
            location: "Available by telephone at 514-398-6246",
            hours: "6 PM-3 AM",
            url: "https://nightline.ssmu.ca/",
            type: "Safety",
            Neighbourhood: "West",
        },
        {
            heading: "Walksafe",
            location: "3480 Mc Tavish St (Room 433)\nMontreal, Quebec H3A 0E7",
            hours: " 9 PM - 3 AM",
            url: "https://walksafe.ssmu.ca/",
            type: "Safety",
            Neighbourhood: "East",
        },
        {
            heading: "Gare d'autocars de Montréal",
            location: "1717 Berri Street\nMontréal, QC\nH2L 4E9",
            hours: "24/7",
            url: "https://www.gamtl.com/en/bienvenue/",
            type: "Getting to Montreal",
            Neighbourhood: "East",
        },
        {
            heading: "VIA Rail Canada",
            location: "895 De La Gauchetière Street West\nMontréal, QC\nH3B 4G1",
            hours: "7 AM - 11 PM",
            url: "https://www.viarail.ca/en",
            type: "Getting to Montreal",
            Neighbourhood: "South",
        },
        {
            heading: "Montréal-Trudeau International Airport",
            location: "YUL Montréal-Trudeau International Airport\nDorval, QC\nH4Y 1H1",
            hours: "24/7",
            url: "https://www.admtl.com/en",
            type: "Getting to Montreal",
            Neighbourhood: "West",
        },
        {
            heading: "Grand Quay - Cruise Terminal",
            location: "Grand Quai du Port de Montréal\nOld Port of Montréal\nMontréal, QC\nH2Y 4B2",
            hours: "11 AM - 7 PM",
            url: "https://www.port-montreal.com/en/cruises",
            type: "Getting to Montreal",
            Neighbourhood: "East",
        },
        {
            heading: "Montréal Infotouriste Centre",
            location: "1255 Peel Street, Suite 100",
            hours: "9 AM - 5 PM",
            url: "https://www.bonjourquebec.com/en-ca",
            type: "Tourism Infopoints",
            Neighbourhood: "South",
        },
        {
            heading: "Tourist Welcome Office in Old Montréal",
            location: "174 Notre-Dame Street East",
            hours: "10 AM - 6 PM",
            url: "https://www.bonjourquebec.com/en-ca",
            type: "Tourism Infopoints",
            Neighbourhood: "West",
        },
        {
            heading: "Montréal Professional Tourist Guides Association",
            location: "C.P. 182, succursale Place d’Armes\nMontréal (Québec)  H2Y 3J4\nCANADA",
            hours: "Hours vary by private guide.",
            url: "https://www.apgt.ca/en/home/",
            type: "Tourism Infopoints",
            Neighbourhood: "East",
        },
        {
            heading: "Firefighting Services",
            location: "Available by telephone at 911",
            hours: "24/7",
            url: "https://spvm.qc.ca/en/Fiches/Details/911",
            type: "Emergency Services",
            Neighbourhood: "South",
        },
        {
            heading: "Ambulance",
            location: "Available by telephone at 911",
            hours: "24/7",
            url: "https://spvm.qc.ca/en/Fiches/Details/911",
            type: "Emergency Services",
            Neighbourhood: "West",
        },
        {
            heading: "Police",
            location: "Available by telephone at 911",
            hours: "24/7",
            url: "https://spvm.qc.ca/en/Fiches/Details/911",
            type: "Emergency Services",
            Neighbourhood: "East",
        },
        {
            heading: "Poison Control Centre",
            location: "1270 Chemin Ste-Foy\nPavillon Jeffrey Hale, 4ème étage\nQuébec, QC G1S 2M4",
            hours: "24/7",
            url: "https://infopoison.ca/centre/centre-anti-poison-du-quebec/",
            type: "Emergency Services",
            Neighbourhood: "West",
        },
        {
            heading: "Ritz-Carlton Montreal",
            location: "1228 Sherbrooke St. West\nMontréal, H3G 1H6 Canada",
            hours: "24/7",
            url: "https://www.ritzcarlton.com/en/hotels/canada/montreal",
            type: "Top Hotels",
            Neighbourhood: "South",
        },
        {
            heading: "Four Seasons Hotel Montreal",
            location: "1440 Rue de la Montagne, Montreal QC H3G 1Z5",
            hours: "24/7",
            url: "https://www.fourseasons.com/montreal/",
            type: "Top Hotels",
            Neighbourhood: "East",
        },

        {
            heading: "Alternative Hostel of Old Montreal",
            location: "358, rue Saint-Pierre\nMontréal, Québec, Canada\nH2Y 2M1",
            hours: "24/7",
            url: "http://www.auberge-alternative.qc.ca/en_US/",
            type: "Top Hotels",
            Neighbourhood: "South",
        },

        {
            heading: "Queen Elizabeth Hotel Fairmont",
            location: "900 Rene Levesque Blvd. W, Montreal - Quebec H3B 4A5",
            hours: "24/7",
            url: "https://www.fairmont.com/queen-elizabeth-montreal/",
            type: "Top Hotels",
            Neighbourhood: "West",
        },

        {
            heading: "Montréal General Hospital",
            location: "1650 Cedar Ave, Montreal, Quebec H3G 1A4, Canada",
            hours: "24/7",
            url: "https://muhc.ca/",
            type: "Hospitals",
            Neighbourhood: "East",
        },
        {
            heading: "Royal Victoria Hospital",
            location: "1001 Decarie Blvd, Montreal, Quebec H4A 3J1, Canada",
            hours: "24/7",
            url: "https://muhc.ca/glen-site",
            type: "Hospitals",
            Neighbourhood: "West",
        },
        {
            heading: "St. Mary's Hospital",
            location: "3830 Av. Lacombe, Montréal, QC H3T 1M5, Canada",
            hours: "24/7",
            url: "https://www.smhc.qc.ca/en/",
            type: "Hospitals",
            Neighbourhood: "South",
        },
        {
            heading: "CHUM",
            location: "1051 Rue Sanguinet, Montréal, QC H2X 3E4, Canada",
            hours: "24/7",
            url: "https://www.chumontreal.qc.ca/joindre-le-chum",
            type: "Hospitals",
            Neighbourhood: "East",
        },
        {
            heading: "Bank of Montreal",
            location: "119, rue Saint-Jacques\nMontreal, Quebec\nH2Y 1L6",
            hours: "9:30 AM - 5 PM",
            url: "https://www.bmo.com/main/personal",
            type: "Banks",
            Neighbourhood: "South",
        },
        {
            heading: "National Bank of Canada",
            location: "Gare Centrale, 895 Rue De La Gauchetière O bureau 90-251, Montréal, QC H3B 4G1, Canada",
            hours: "9 AM - 4 PM",
            url: "https://www.nbc.ca/content/bnc/en/accueil/particuliers.html",
            type: "Banks",
            Neighbourhood: "West",
        },
        {
            heading: "Toronto Dominion  Canada Trust",
            location: "800 René-Lévesque Blvd W, Montreal, Quebec H3B 1X9, Canada",
            hours: "9 AM - 6 PM",
            url: "https://www.td.com/ca/en/personal-banking/",
            type: "Banks",
            Neighbourhood: "East",
        },
        {
            heading: "Desjardins",
            location: "South Tower, 1 Complexe Desjardins, Montréal, QC H5B 1B2, Canada",
            hours: "8 AM - 6 PM",
            url: "https://www.desjardins.com/",
            type: "Banks",
            Neighbourhood: "South",
        },
        {
            heading: "P$ Service Mobile",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://www.agencemobilitedurable.ca/en/practical-info/pmobileservice.html",
            type: "Helpful Apps",
            Neighbourhood: "West",
        },
        {
            heading: "Transit: Go Your Own Way",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://transitapp.com/",
            type: "Helpful Apps",
            Neighbourhood: "East",
        },
        {
            heading: "Canadian Broadcasing Company News App",
            location: "Available through the App on iPhone and Android",
            hours: "24/7",
            url: "https://www.cbc.ca/newsapp/",
            type: "Helpful Apps",
            Neighbourhood: "South",
        }

    ]
    await models.Service.bulkCreate(Service)

    const AllService = [
        {
            type: "Transportation in the City",
            imgPath: "https://images.unsplash.com/photo-1569596602585-8d101a0d150b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
            description: "It's easy to get around this mid-sized city, no matter what the weather! Hop on a Bixi bike, check out the art in underground Metro stations around the city, or call an Uber after a long day sightseeing. You've got options!",

        },
        {
            type: "Outdoor Fun",
            imgPath: "https://images.unsplash.com/photo-1574607076416-1b1cbd1846a8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            description: "Enjoy Montreal like a local! Grab a scooter or e-bike for those hills, or learn to love winter with a nordic ski rental on the mountain and a pair of skates by the St.Lawrence river. Have fun!",

        },
        {
            type: "Safety",
            imgPath: "https://images.unsplash.com/photo-1595277542060-6324da6d30f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1153&q=80",
            description: "We all need a hand sometimes. Volunteers are available for crisis situations, and the Nightline is open to any call for any reason. Walksafe will send a car or a buddy to help you get home after a late night, for free. ",

        },
        {
            type: "Getting to Montreal",
            imgPath: "https://images.unsplash.com/photo-1485833380722-ff5c9b742ce4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
            description: "Planes, trains, and automobiles! You can even take a ferry to beautiful Montreal. Choose what works for your budget and schedule. ",

        },
        {
            type: "Tourism Infopoints",
            imgPath: "https://images.unsplash.com/photo-1532299039866-065669a2d5df?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1276&q=80",
            description: "Offices around the city are open to help you plan your trip and navigate the city. Visit to ask questions and get visitor materials in English or French. ",

        },
        {
            type: "Emergency Services",
            imgPath: "https://images.unsplash.com/photo-1593534800980-388d57cc0b87?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            description: "In case of an emergency, call 911 to reach all emergency services. Service is multilingual, so don't hesitate to call. ",

        },
        {
            type: "Top Hotels",
            imgPath: "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
            description: "Montreal is brimming with hotels for every style and budget: luxury or boutique, designer or hostel, you're sure to find somewhere you'll feel at home. ",

        },
        {
            type: "Hospitals",
            imgPath: "https://images.unsplash.com/photo-1555108004-a9183c23169e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            description: "We wish you a safe stay in Montreal, but life can be unpredicatable. If you need to seek medical attention, rest assured that Montreal is home to a large number of hospitals, many of which are internationally ranked in their specialties. ",

        },
        {
            type: "Banks",
            imgPath: "https://images.unsplash.com/photo-1512763613895-de7207475439?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1365&q=80",
            description: "Unfortunately, travel costs! While Montreal is famous for being an affordable city, you'l still need to withdraw at some point in your stay. Trust any of the following institutions, which are ready to serve you in English ro French. ",

        },
        {
            type: "Helpful Apps",
            imgPath: "https://images.unsplash.com/photo-1621983062294-e5a7ce79a990?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            description: "Stay informed with these hand smartphone apps. Find your way in the city with Transit, pay for parking from the comfort of your table with P$ service mobile, and check in o current events around you with Canada's leading news source. ",

        }

    ]
    await models.AllService.bulkCreate(AllService)

    const Itineraries = [
        {
            imgPath: "https://images.unsplash.com/photo-1531338498331-ad43305c982f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            description: "Much of the most beautiful architecture in Montreal is thanks to a rich collection of churches dating back to the original settlement of Canada, long before it became a country. Get your fill of history history, art, and nature on our tour through some of the most iconic places of worship in the city. Start with St.Joseph's Oratory, where you can walk up the famous 283 steps. This basilica is home to a religious relic, the heart of beloved local saint Brother Andre. The Basilica warmly welcomes visitors of all faiths, and the view is worth the climb. Next you can stop at the cemetery of Mont-Royal just up th road, where famous Canadians such as Mordecai Richler and Leonard Cohen are buried. Make your way down to the Old Port, where you'll find a piece of France in Notre Dame Basilica. The last step on the tour, Our Lady of the Harbour offers a wonderful view of the St.Lawrence. It is said that from this church, ships at sea were guided safely home. You'll be happy to know that from this location you can fantastic restaurants for any meal of the day, as you'll surely have worked up an appetite.",
            heading: "For the Church Lover",
            duration: "4 Hours",
            imgPathMap: "https://i.stack.imgur.com/coL96.png"
        },
        {
            imgPath: "https://images.unsplash.com/photo-1570474640932-c5dfbeeb2706?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            description: "For the traveller that can't get enough of art and culture, or for a rainy day, choose the museums and galleries of Montreal. Start at the small but might McCord museum, where you'll learn about Canadian artists and journalists. As you walk along Sherbrooke street to La Guilde, you'll see the iconic laneway of McGill University. After the small and local collection at La Guilde, you can enjoy a coffee before taking in the permanent collection in the Musee des Beaux-Arts. Then walk towards the port, where you'll find an incredible rotating Anthropology and History exhibits.",
            heading: "For the Intellectual",
            duration: "5 Hours",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
        },
        {
            imgPath: "https://images.unsplash.com/photo-1570474644749-dc5edd36353d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            description: "If you're not a city person, fear not! Montreal offers plenty of escapes from the chaos, all accessibly by public transport. Start with breakfast at Jean Talon Market, where you'll find in season product and baked goods, as well as a dangerous selection of artisinal cheeses. Take the metro to the Botanical Gardens. Don't worry if the weather isn't perfect, the greenhouses offer hours of enjoyment. By this time you should be ready for lunch, and you can make your way to the Lachine Canal for a bite to eat. Once recharged, use your energy to walk up Mont-Royal. You won't want to miss the lookout point, where you can admire how much ground you covered!",
            heading: "For the Nature Lover",
            duration: "4 Hours",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
        },

        {
            imgPath: "https://images.unsplash.com/photo-1496199846480-d952d65ee514?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
            description: "We all have a friend that can't end a trip without the perfect picture. Take them to the most influencial exhibits of the year in this immersive art tour. Start at Oasis, where you'll walk through the interactive Van Gogh exhibit. Next, pay tribute to Frida Kahlo at the Arsenal Art Contemporain. If you still haven't gotten the perfect shot, fear not! Le Saint Motel is a selfie studie offering 13 themed rooms. Lastly, to situate yourself in the perfect neighbourhood for 5-7, head to the Phi Centre for the iconic Infinity Mirror Rooms exhibition at the Phi Centre.",
            heading: "For the Influencer",
            duration: "6 Hours",
            imgPathMap: "https://i.stack.imgur.com/coL96.png",
        },
    ]

    await models.Itineraries.bulkCreate(Itineraries)

    const poiEventsJoinTable = [
        {
            poiId: 1,
            eventId:1,
        },
        {
            poiId: 2,
            eventId:2,
        },
        {
            poiId: 3,
            eventId:3,
        },
        {
            poiId: 3,
            eventId:4,
        },
        {
            poiId: 1,
            eventId:5,
        },
        {
            poiId: 1,
            eventId:6,
        },
        {
            poiId: 4,
            eventId:7,
        },
        {
            poiId: 5,
            eventId:8,
        },
        {
            poiId: 8,
            eventId:9,
        },
        {
            poiId: 6,
            eventId:10,
        },
        
        {
            poiId: 9,
            eventId:11,
        },
        {
            poiId: 7,
            eventId:12,
        },
        {
            poiId: 10,
            eventId:13,
        },
        {
            poiId: 13,
            eventId:14,
        },
        {
            poiId: 20,
            eventId:15,
        },
        {
            poiId: 16,
            eventId:16,
        },
        {
            poiId: 19,
            eventId:17,
        },
        {
            poiId: 31,
            eventId:18,
        },
        {
            poiId: 32,
            eventId:19,
        },


    ]


    await models.poiEventsJoinTable.bulkCreate(poiEventsJoinTable)
}